"""empty message

Revision ID: c266e2edafec
Revises: 
Create Date: 2017-02-09 15:29:27.228959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c266e2edafec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_akun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('date_reg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akun_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['akun_id'], ['tb_akun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_file')
    op.drop_table('tb_akun')
    # ### end Alembic commands ###
